
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres # usuário do postgreSQL
    password: root # a senha do usuário
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update # drop, update
    properties:
      hibernate.format_sql: true
